server:
  port: 8888
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
            uri: file:///C:/Users/vidhul.s/Documents/IdeaProjects/ms/configfiles-main
            clone-on-start: true
            default-label: master
#          uri: "https://github.com/rgupta00/configfiles.git"
#          clone-on-start: true
#          default-label: main
#          force-pull: true
#          timeout: 5
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true


