apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: vidhuls/helloworld:latest  # Ensure correct image version
          ports:
            - containerPort: 8080
          imagePullPolicy: Always  # Ensures latest image is pulled on restart
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Creates an AWS ELB (Check IAM permissions)
