apiVersion: v1
kind: Secret
metadata:
  name: bookApp-secret
  namespace: qa
type: Opaque
data:
  DB_USER: dXNlcg==  # Base64 encoded value of "user"
  DB_PASS: cGFzc3dvcmQ=  # Base64 encoded value of "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: bookApp-secret
  namespace: dev
type: Opaque
data:
  DB_USER: ZGV2dXNlcg==  # Base64 encoded value of "devuser"
  DB_PASS: ZGV2cGFzcw==  # Base64 encoded value of "devpass"
