server:
  port: 8761  # Change this for each microservice to avoid port conflicts

spring:
  application:
    name: NAMING_SERVER
  profiles:
    active: dev  # Default profile (dev, prod, etc.)
  micrometer:
    registry:
      prometheus:
        enabled: true
  sleuth:
    sampler:
      probability: 1.0  # 100% sampling rate for tracing
    web:
      client:
        enabled: true  # Enable tracing for HTTP client requests
    zipkin:
      base-url: http://localhost:9411/api/v2/spans

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  # The server does not register itself
    fetch-registry: false  # It does not need to fetch registry data
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  metrics:
    enabled: true

logging:
  level:
    org.springframework.cloud: INFO