server:
  port: 8100  # Change this for each microservice to avoid port conflicts

spring:
  security:
    basic:
      enabled: false
  application:
    name: CURRENCY-CONVERT
profiles:
  active: dev  # Default profile (dev, prod, etc.)
  # Micrometer Tracing Configuration
sleuth:
  sampler:
    probability: 1.0  # Trace all requests, adjust as needed
  web:
    client:
      enabled: true  # Enable tracing for HTTP clients
  zipkin:
    base-url: http://localhost:9411/api/v2/spans  # Zipkin's endpoint
    sender:
      type: web  # Use web for Zipkin HTTP transport
  micrometer:
    registry:
      prometheus:
        enabled: true


eureka:
  instance:
    prefer-ip-address: true  # Use IP instead of hostname
    instance-id: ${spring.cloud.client.ip-address}:${server.port}  # Ensures a unique identifier
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0  # Ensures all requests are traced
  zipkin:
    tracing:
      endpoint: http://host.docker.internal:9411/api/v2/spans  # If running Zipkin in Docker
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    enabled: true

logging:
  level:
    org.springframework.cloud: INFO